//-------------------------------------------------------
// Autogenerated from 'c12m4_barn_ralimu.vmf'
//-------------------------------------------------------
C12M4RalimuSurvivalCar <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.ralimu_survival_car,
			EntityGroup.SpawnTables.ralimu_survival_carglass,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.ralimu_survival_carglass,
			EntityGroup.SpawnTables.ralimu_survival_car,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			ralimu_survival_car =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -3, -90, 0 )
					body = "0"
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "$fademaxdist"
					fademindist = "$fademindist"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					maxdxlevel = "0"
					mindxlevel = "0"
					minhealthdmg = "0"
					model = "models/props_vehicles/cara_95sedan.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "138 37 9"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_car"
					origin = Vector( 11271.3, -6684.25, -91.6166 )
				}
			}
			ralimu_survival_carglass =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -3, -90, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "$fademaxdist"
					fademindist = "$fademindist"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
				//	health = "5"
					MaxAnimTime = "10"
					maxdxlevel = "0"
					MinAnimTime = "5"
					mindxlevel = "0"
					model = "models/props_vehicles/cara_95sedan_glass.mdl"
					parentname = "ralimu_survival_car"
					PerformanceMode = "0"
					physdamagescale = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "ralimu_survival_carglass"
					origin = Vector( 11271.3, -6684.25, -91.6166 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // C12M4RalimuSurvivalCar

RegisterEntityGroup( "C12M4RalimuSurvivalCar", C12M4RalimuSurvivalCar )
