//-------------------------------------------------------
// Autogenerated from 'c12m4_barn_ralimu.vmf'
//-------------------------------------------------------
C12M4RalimuSurvival <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.ralimu_survival_items10,
			EntityGroup.SpawnTables.ralimu_survival_items11,
			EntityGroup.SpawnTables.ralimu_survival_items12,
			EntityGroup.SpawnTables.ralimu_survival_items13,
			EntityGroup.SpawnTables.ralimu_survival_items14,
			EntityGroup.SpawnTables.ralimu_survival_items15,
			EntityGroup.SpawnTables.ralimu_survival_items16,
			EntityGroup.SpawnTables.ralimu_survival_items17,
			EntityGroup.SpawnTables.ralimu_survival_items18,
			EntityGroup.SpawnTables.ralimu_survival_items19,
			EntityGroup.SpawnTables.ralimu_survival_items20,
			EntityGroup.SpawnTables.ralimu_survival_items21,
			EntityGroup.SpawnTables.ralimu_survival_items22,
			EntityGroup.SpawnTables.ralimu_survival_radio,
			EntityGroup.SpawnTables.ralimu_survival_items29,
			EntityGroup.SpawnTables.ralimu_survival_items30,
			EntityGroup.SpawnTables.ralimu_survival_props,
			EntityGroup.SpawnTables.ralimu_survival_props1,
			EntityGroup.SpawnTables.ralimu_survival_items34,
			EntityGroup.SpawnTables.ralimu_survival_items42,
			EntityGroup.SpawnTables.ralimu_survival_items43,
			EntityGroup.SpawnTables.ralimu_survival_props2,
			EntityGroup.SpawnTables.ralimu_survival_items47,
			EntityGroup.SpawnTables.ralimu_survival_items48,
			EntityGroup.SpawnTables.ralimu_survival_items49,
			EntityGroup.SpawnTables.ralimu_survival_items50,
			EntityGroup.SpawnTables.ralimu_survival_props3,
			EntityGroup.SpawnTables.ralimu_survival_props4,
			EntityGroup.SpawnTables.ralimu_survival_props5,
			EntityGroup.SpawnTables.ralimu_survival_items58,
			EntityGroup.SpawnTables.ralimu_survival_items59,
			EntityGroup.SpawnTables.ralimu_survival_props_unused,
			EntityGroup.SpawnTables.ralimu_survival_props_unused1,
			EntityGroup.SpawnTables.ralimu_survival_props_unused2,
			EntityGroup.SpawnTables.ralimu_survival_props_unused3,
			EntityGroup.SpawnTables.ralimu_survival_props_unused4,
			EntityGroup.SpawnTables.ralimu_survival_props_unused5,
			EntityGroup.SpawnTables.ralimu_survival_items74,
			EntityGroup.SpawnTables.ralimu_survival_props6,
			EntityGroup.SpawnTables.ralimu_survival_props7,
			EntityGroup.SpawnTables.ralimu_survival_props8,
			EntityGroup.SpawnTables.ralimu_survival_props9,
			EntityGroup.SpawnTables.ralimu_survival_items77,
			EntityGroup.SpawnTables.ralimu_survival_items78,
			EntityGroup.SpawnTables.ralimu_survival_items79,
			EntityGroup.SpawnTables.ralimu_survival_props10,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.ralimu_survival_vphysics_clip,
			EntityGroup.SpawnTables.ralimu_survival_template,
			EntityGroup.SpawnTables.ralimu_survival_props10,
			EntityGroup.SpawnTables.ralimu_survival_props9,
			EntityGroup.SpawnTables.ralimu_survival_props8,
			EntityGroup.SpawnTables.ralimu_survival_props7,
			EntityGroup.SpawnTables.ralimu_survival_props6,
			EntityGroup.SpawnTables.ralimu_survival_props5,
			EntityGroup.SpawnTables.ralimu_survival_props4,
			EntityGroup.SpawnTables.ralimu_survival_props3,
			EntityGroup.SpawnTables.ralimu_survival_props2,
			EntityGroup.SpawnTables.ralimu_survival_props1,
			EntityGroup.SpawnTables.ralimu_survival_props,
			EntityGroup.SpawnTables.ralimu_survival_props_unused5,
			EntityGroup.SpawnTables.ralimu_survival_props_unused4,
			EntityGroup.SpawnTables.ralimu_survival_props_unused3,
			EntityGroup.SpawnTables.ralimu_survival_props_unused2,
			EntityGroup.SpawnTables.ralimu_survival_props_unused1,
			EntityGroup.SpawnTables.ralimu_survival_props_unused,
			EntityGroup.SpawnTables.ralimu_survival_positions3,
			EntityGroup.SpawnTables.ralimu_survival_positions2,
			EntityGroup.SpawnTables.ralimu_survival_positions1,
			EntityGroup.SpawnTables.ralimu_survival_positions,
			EntityGroup.SpawnTables.ralimu_survival_entitygroup_relay,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			ralimu_survival_items =
			{
				SpawnInfo =
				{
					classname = "weapon_vomitjar_spawn"
					angles = Vector( 0, 305.5, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11156, -4172, -18.8595 )
				}
			}
			ralimu_survival_items1 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 89.0057, 84.4455, -60.0658 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10803, -7392, -33 )
				}
			}
			ralimu_survival_items2 =
			{
				SpawnInfo =
				{
					classname = "weapon_rifle_sg552_spawn"
					angles = Vector( 0, 240, -90 )
					count = "5"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11017.8, -5901.87, -26.9759 )
				}
			}
			ralimu_survival_items3 =
			{
				SpawnInfo =
				{
					classname = "weapon_hunting_rifle_spawn"
					angles = Vector( 0, 240, -90 )
					count = "5"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11061, -4348, 122 )
				}
			}
			ralimu_survival_items4 =
			{
				SpawnInfo =
				{
					classname = "weapon_pistol_magnum_spawn"
					angles = Vector( 0, 61.5, 90 )
					count = "1"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11068.5, -4179, -23 )
				}
			}
			ralimu_survival_items5 =
			{
				SpawnInfo =
				{
					classname = "weapon_rifle_ak47_spawn"
					angles = Vector( 0, 335, -91.5 )
					body = "0"
					count = "2"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10829, -7383, -34 )
				}
			}
			ralimu_survival_items6 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 345, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11008.4, -7494, -63 )
				}
			}
			ralimu_survival_items7 =
			{
				SpawnInfo =
				{
					classname = "weapon_autoshotgun_spawn"
					angles = Vector( -59.8154, 263.026, -83.964 )
					body = "0"
					count = "2"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10711, -5697, -56 )
				}
			}
			ralimu_survival_items8 =
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 38.5, 90 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11028, -5780, -39 )
				}
			}
			ralimu_survival_items9 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 87.6523, 295.566, -89.0662 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10896.2, -5947.91, -35 )
				}
			}
			ralimu_survival_items10 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.219727, 300.454, 0.131836 )
					damagetoenablemotion = "0"
					damagetype = "0"
					disablex360 = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 10881.5, -4590.25, -53.0938 )
				}
			}
			ralimu_survival_items11 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 345, 0 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiaScale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_equipment/oxygentank01.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 11023.3, -5873, -64 )
				}
			}
			ralimu_survival_items12 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 300.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 10752.9, -7436.88, -57.0625 )
				}
			}
			ralimu_survival_items13 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.043945, 275.405, 0.219727 )
					damagetoenablemotion = "0"
					damagetype = "0"
					disablex360 = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11144.1, -7748.84, -1.125 )
				}
			}
			ralimu_survival_items14 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 300.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 10813.9, -9066.72, -1.09375 )
				}
			}
			ralimu_survival_items15 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 300.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 10914, -4608.06, 98.8438 )
				}
			}
			ralimu_survival_items16 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -0.659185, 193.096, 0.175781 )
					damagetoenablemotion = "0"
					damagetype = "0"
					disablex360 = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 10872.4, -4114.22, 98.8438 )
				}
			}
			ralimu_survival_items17 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -0.527335, 344.971, -0.703117 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_junk/propanecanister001a.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 10879.9, -4099.84, 99.3125 )
				}
			}
			ralimu_survival_items18 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -0.263663, 345.015, -0.439444 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_junk/propanecanister001a.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11152.3, -7779.94, -0.625 )
				}
			}
			ralimu_survival_items19 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -0.351553, 345.015, -0.571294 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_junk/propanecanister001a.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 10796.5, -9070.72, -0.59375 )
				}
			}
			ralimu_survival_items20 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 345, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					origin = Vector( 10641.3, -8796.39, -11.768 )
				}
			}
			ralimu_survival_items21 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 345, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					origin = Vector( 11034, -5686.43, -63.768 )
				}
			}
			ralimu_survival_items22 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 345, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "257"
					targetname = "ralimu_survival_items"
					origin = Vector( 11188.2, -4059.93, 88.232 )
				}
			}
			ralimu_survival_items23 =
			{
				SpawnInfo =
				{
					classname = "weapon_melee_spawn"
					angles = Vector( 0, 78, 90 )
					count = "1"
					disableshadows = "1"
					melee_weapon = "shovel,pitchfork,knife,crowbar,frying_pan"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11053, -4062, -165 )
				}
			}
			ralimu_survival_items24 =
			{
				SpawnInfo =
				{
					classname = "weapon_melee_spawn"
					angles = Vector( 0, 270, 90 )
					count = "1"
					disableshadows = "1"
					melee_weapon = "fireaxe,machete,frying_pan,pitchfork,baseball_bat"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11056, -4077, 95 )
				}
			}
			ralimu_survival_positions =
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 15, 0 )
					GameMode = "survival"
					Order = "3"
					SurvivorName = "Louis"
					targetname = "ralimu_survival_positions"
					origin = Vector( 10828, -6044, -60 )
				}
			}
			ralimu_survival_positions1 =
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 0, 0 )
					GameMode = "survival"
					Order = "2"
					SurvivorName = "Francis"
					targetname = "ralimu_survival_positions"
					origin = Vector( 10816, -5980, -60 )
				}
			}
			ralimu_survival_positions2 =
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 345, 0 )
					GameMode = "survival"
					Order = "1"
					SurvivorName = "Bill"
					targetname = "ralimu_survival_positions"
					origin = Vector( 10816, -5928, -60 )
				}
			}
			ralimu_survival_positions3 =
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 330, 0 )
					GameMode = "survival"
					Order = "4"
					SurvivorName = "Zoey"
					targetname = "ralimu_survival_positions"
					origin = Vector( 10824, -5880, -60 )
				}
			}
			ralimu_survival_radio =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180.5, 0 )
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/terror/hamradio.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "ralimu_survival_radio"
					origin = Vector( 11020.5, -5990, -64 )
				}
			}
			ralimu_survival_items25 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 0, 0 )
					body = "0"
					count = "1"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 11020, -6025.1, -59 )
				}
			}
			ralimu_survival_radio_hint =
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					angles = Vector( 0, 0, 0 )
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "0"
					hint_caption = "#L4D_Instructor_explain_panic_button2"
					hint_color = "225 225 225"
					hint_display_limit = "0"
					hint_forcecaption = "0"
					hint_icon_offscreen = "icon_alert_red"
					hint_icon_offset = "10"
					hint_icon_onscreen = "icon_alert_red"
					hint_instance_type = "1"
					hint_local_player_only = "0"
					hint_name = "ralimu_c12m2_explain_survival"
					hint_nooffscreen = "0"
					hint_pulseoption = "0"
					hint_range = "300"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "0"
					hint_target = "ralimu_survival_radio"
					hint_timeout = "0"
					targetname = "ralimu_survival_radio_hint"
					origin = Vector( 10912, -5964, -16 )
				}
			}
			ralimu_survival_items26 =
			{
				SpawnInfo =
				{
					classname = "weapon_grenade_launcher_spawn"
					angles = Vector( 0, 0, 90.5 )
					count = "5"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10994, -6068, -44 )
				}
			}
			ralimu_survival_radio_button =
			{
				SpawnInfo =
				{
					classname = "script_func_button"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					glow = "ralimu_survival_radio"
					health = "0"
					lip = "0"
					locked_sentence = "0"
					locked_sound = "0"
					movedir = "0 0 0"
					origin = Vector( 11022.3, -5995.1, -57.48 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					sounds = "0"
					spawnflags = "1024"
					speed = "1"
					targetname = "ralimu_survival_radio_button"
					unlocked_sentence = "0"
					unlocked_sound = "0"
					vrad_brush_cast_shadows = "0"
					wait = "0"
					extent = Vector( 12, 18, 6.50015 )
					connections =
					{
						OnPressed =
						{
							cmd1 = "ralimu_survival_radio_hintKill0-1"
							cmd2 = "ralimu_survival_radioStopGlowing0-1"
							cmd3 = "!selfKill0.1-1"
							cmd4 = "directorBeginScriptc12m4_survival_ralimu1-1"
							cmd5 = "directorPanicEvent1-1"
							cmd6 = "ralimu_survival_radio_sparksSparkOnce0-1"
							cmd7 = "ralimu_survival_radio_sparksSparkOnce1-1"
							cmd8 = "ralimu_survival_radio_sound_casePickRandom1-1"
							cmd9 = "ralimu_survival_radio_sparksAddOutputtraillength 20.5-1"
							cmd10 = "ralimu_survival_radio_sparksAddOutputmagnitude 20.5-1"
						}
					}
				}
			}
			ralimu_survival_items27 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 87.6523, 235.566, -89.0662 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10911, -5945, -35 )
				}
			}
			ralimu_survival_items28 =
			{
				SpawnInfo =
				{
					classname = "weapon_sniper_scout_spawn"
					angles = Vector( 3.89611, 239.923, -92.2535 )
					count = "5"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10836.7, -9786, -75 )
				}
			}
			ralimu_survival_items29 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 300.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 10842.2, -9755.14, -64.9797 )
				}
			}
			ralimu_survival_items30 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 247.954, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 10856, -9758, -64 )
				}
			}
			ralimu_survival_items31 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( -14, 124, -90 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11007, -7486, -66 )
				}
			}
			ralimu_survival_items32 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 89.0057, 84.4455, -60.0658 )
					body = "0"
					disableshadows = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10818, -7393, -34 )
				}
			}
			ralimu_survival_items33 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0.0843647, 89.9526, -0.0121748 )
					body = "0"
					disableshadows = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10818, -7388, -35 )
				}
			}
			ralimu_survival_props =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 286.5, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1400"
					fademindist = "1200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_debris/barricade_tall03a.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 10431, -3588, -11.2111 )
				}
			}
			ralimu_survival_props1 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 83.5, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1400"
					fademindist = "1200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_debris/barricade_tall03a.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 10487, -3552, -5 )
				}
			}
			ralimu_survival_finder_ammo2 =
			{
				SpawnInfo =
				{
					classname = "point_entity_finder"
					angles = Vector( 0, 0, 0 )
					filtername = "ralimu_survival_finder_ammo_filter"
					method = "0"
					referencename = "ammo_spawn2_template"
					targetname = "ralimu_survival_finder_ammo2"
					origin = Vector( 10920, -5984, 8 )
					connections =
					{
						OnFoundEntity =
						{
							cmd1 = "!callerKill0-1"
						}
					}
				}
			}
			ralimu_survival_finder_ammo_filter2 =
			{
				SpawnInfo =
				{
					classname = "filter_activator_name"
					angles = Vector( 0, 0, 0 )
					filtername = "ammo_spawn2"
					negated = "0"
					targetname = "ralimu_survival_finder_ammo_filter2"
					origin = Vector( 10904, -5984, 8 )
				}
			}
			ralimu_survival_items34 =
			{
				SpawnInfo =
				{
					classname = "weapon_ammo_spawn"
					angles = Vector( 0, 325, 0 )
					body = "0"
					count = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					model = "models/props_unique/spawn_apartment/coffeeammo.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 10918, -5978, -36.826 )
				}
			}
			ralimu_survival_items35 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 79, 0 )
					body = "0"
					count = "1"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 11024, -6030, -59 )
				}
			}
			ralimu_survival_items36 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 315, 0 )
					body = "0"
					count = "1"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 11018, -6034, -59 )
				}
			}
			ralimu_survival_items37 =
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 69, 90 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11028, -5788, -39 )
				}
			}
			ralimu_survival_items38 =
			{
				SpawnInfo =
				{
					classname = "weapon_upgradepack_incendiary_spawn"
					angles = Vector( 0, 315, 0 )
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10807, -5682, -29 )
				}
			}
			ralimu_survival_items39 =
			{
				SpawnInfo =
				{
					classname = "weapon_upgradepack_explosive_spawn"
					angles = Vector( 0, 62, 0 )
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10819, -5683, -29 )
				}
			}
			ralimu_survival_entitygroup_relay =
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					angles = Vector( 0, 0, 0 )
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_entitygroup_relay"
					origin = Vector( 10992, -6000, -36 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "ralimu_survival_templateForceSpawn0-1"
						}
					}
				}
			}
			ralimu_survival_items40 =
			{
				SpawnInfo =
				{
					classname = "weapon_vomitjar_spawn"
					angles = Vector( 0, 154, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11149, -4168, -18.8595 )
				}
			}
			ralimu_survival_navattrs =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					origin = Vector( 10712, -5892, -8 )
					precise = "0"
					spawnflags = "8192"
					stairs = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 24, 56, 56 )
				}
			}
			ralimu_survival_items41 =
			{
				SpawnInfo =
				{
					classname = "weapon_rifle_m60_spawn"
					angles = Vector( 0, 300, 90 )
					body = "0"
					count = "5"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10885, -6061, 162 )
				}
			}
			ralimu_survival_items42 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 300.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 11943.1, -7342.54, -83.9668 )
				}
			}
			ralimu_survival_items43 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.043945, 275.405, 0.219727 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 11938.3, -7331.91, -83.0848 )
				}
			}
			ralimu_survival_items44 =
			{
				SpawnInfo =
				{
					classname = "weapon_upgradepack_incendiary_spawn"
					angles = Vector( 0, 333, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11032, -4310.93, 121 )
				}
			}
			ralimu_survival_items45 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0, 333, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11197.5, -4517.6, 122.312 )
				}
			}
			ralimu_survival_items46 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0, 255, 0 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10962, -4592, -63 )
				}
			}
			ralimu_survival_props2 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					maxanimtime = "10"
					minanimtime = "5"
					model = "models/props/cs_militia/ladderrung.mdl"
					physdamagescale = "1.0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "ralimu_survival_props"
					origin = Vector( 11264, -4507, -280 )
				}
			}
			ralimu_survival_navattrs1 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10888, -5892, -8 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "8192"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 152, 216, 56 )
				}
			}
			ralimu_survival_items47 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -110, 7, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11218, -4564, -163 )
				}
			}
			ralimu_survival_items48 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 15, 355, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11205, -4586, -164 )
				}
			}
			ralimu_survival_items49 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0.263672, 330.454, 0.175781 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablex360 = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11205, -4521, -155 )
				}
			}
			ralimu_survival_items50 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -89.475, 29.8531, -59.6784 )
					damagetoenablemotion = "0"
					damagetype = "0"
					disablex360 = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11207, -4504, -163 )
				}
			}
			ralimu_survival_items51 =
			{
				SpawnInfo =
				{
					classname = "weapon_defibrillator_spawn"
					angles = Vector( 0, 90, 0 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11038, -4073, -165 )
				}
			}
			ralimu_survival_items52 =
			{
				SpawnInfo =
				{
					classname = "weapon_defibrillator_spawn"
					angles = Vector( 0, 170, 0 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11064, -4077, -165 )
				}
			}
			ralimu_survival_items53 =
			{
				SpawnInfo =
				{
					classname = "weapon_adrenaline_spawn"
					angles = Vector( 0, 240, 0 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11030, -4078, -165 )
				}
			}
			ralimu_survival_props3 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					maxanimtime = "10"
					minanimtime = "5"
					model = "models/props/cs_militia/ladderrung.mdl"
					physdamagescale = "1.0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "ralimu_survival_props"
					origin = Vector( 11245, -4510, -195 )
				}
			}
			ralimu_survival_props4 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1200"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 11261, -4509, -211 )
				}
			}
			ralimu_survival_props5 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1200"
					fadescale = "0.5"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 11254, -4509, -202 )
				}
			}
			ralimu_survival_items54 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 120, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10696, -5720, -35 )
				}
			}
			ralimu_survival_items55 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 45, 330, -90 )
					body = "0"
					count = "1"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 11013, -6028, -63 )
				}
			}
			ralimu_survival_items56 =
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 124, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10966, -8733, 27 )
				}
			}
			ralimu_survival_items57 =
			{
				SpawnInfo =
				{
					classname = "weapon_smg_silenced_spawn"
					angles = Vector( 0, 255, -87 )
					count = "5"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10988, -8708, 24.0588 )
				}
			}
			ralimu_survival_items58 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 75.2568, 241.784, 1.89927 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 11009.9, -8718.64, 32 )
				}
			}
			ralimu_survival_items59 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -14.1018, 274.345, -15.4225 )
					body = "0"
					damagetoenablemotion = "0"
					damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disablex360 = "0"
					drawinfastreflection = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					inertiascale = "1.0"
					massscale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_junk/gascan001a.mdl"
					nodamageforces = "0"
					performancemode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					origin = Vector( 11032, -8696, 37 )
				}
			}
			ralimu_survival_items60 =
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 319, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10974, -8736, 27 )
				}
			}
			ralimu_survival_items61 =
			{
				SpawnInfo =
				{
					classname = "weapon_chainsaw_spawn"
					angles = Vector( 0.527344, 169.949, 0.307617 )
					count = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10932, -8700, 27 )
				}
			}
			ralimu_survival_items62 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0, 263, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10888, -8559, 23 )
				}
			}
			ralimu_survival_items63 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0, 20, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10896, -8560, 23 )
				}
			}
			ralimu_survival_items64 =
			{
				SpawnInfo =
				{
					classname = "weapon_pistol_magnum_spawn"
					angles = Vector( 0, 119, 90 )
					count = "1"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "0"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10904, -8553.79, 23 )
				}
			}
			ralimu_survival_items65 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 89.0057, 204.445, -60.0658 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10793, -7397, -33 )
				}
			}
			ralimu_survival_items66 =
			{
				SpawnInfo =
				{
					classname = "weapon_pumpshotgun_spawn"
					angles = Vector( 0, 76.5, 90 )
					count = "2"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 11197, -4565, 123.299 )
				}
			}
			ralimu_survival_items67 =
			{
				SpawnInfo =
				{
					classname = "weapon_shotgun_chrome_spawn"
					angles = Vector( 0, 30, -87 )
					count = "5"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10943, -8728, 24.0588 )
				}
			}
			ralimu_survival_props_unused =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 0, 320, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "2400"
					fademindist = "2000"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_vehicles/train_box.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "198 192 140"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 11840, -8064, -80 )
				}
			}
			ralimu_survival_props_unused1 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 90, 165, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1250"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 10708, -8848, 20 )
				}
			}
			ralimu_survival_props_unused2 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 90, 0, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1250"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 10616, -8912, 20 )
				}
			}
			ralimu_survival_props_unused3 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 90, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1250"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 10592, -8872, 20 )
				}
			}
			ralimu_survival_props_unused4 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 90, 180, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1250"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 10608, -8912, 20 )
				}
			}
			ralimu_survival_props_unused5 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_disabled"
					angles = Vector( 90, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1250"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props/de_nuke/crate_small.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props_unused"
					texframeindex = "0"
					origin = Vector( 10596, -8920, 84 )
				}
			}
			ralimu_survival_radio_sparks =
			{
				SpawnInfo =
				{
					classname = "env_spark"
					angles = Vector( 0, 0, 0 )
					magnitude = "1"
					maxdelay = "0"
					spawnflags = "0"
					targetname = "ralimu_survival_radio_sparks"
					traillength = "1"
					origin = Vector( 11020, -5992, -56 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "ralimu_survival_templateForceSpawn0-1"
						}
					}
				}
			}
			ralimu_survival_radio_sound1 =
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					angles = Vector( 0, 0, 0 )
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "ambient/energy/zap1.wav"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "1250"
					spawnflags = "49"
					spindown = "0"
					spinup = "0"
					targetname = "ralimu_survival_radio_sound1"
					volstart = "0"
					origin = Vector( 11020, -5976, -24 )
				}
			}
			ralimu_survival_radio_sound_case =
			{
				SpawnInfo =
				{
					classname = "logic_case"
					angles = Vector( 0, 0, 0 )
					targetname = "ralimu_survival_radio_sound_case"
					origin = Vector( 11020, -5992, -40 )
					connections =
					{
						OnCase02 =
						{
							cmd1 = "ralimu_survival_radio_sound2PlaySound0-1"
						}
						OnCase03 =
						{
							cmd1 = "ralimu_survival_radio_sound3PlaySound0-1"
						}
						OnCase01 =
						{
							cmd1 = "ralimu_survival_radio_sound1PlaySound0-1"
						}
					}
				}
			}
			ralimu_survival_radio_sound2 =
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					angles = Vector( 0, 0, 0 )
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "ambient/energy/zap2.wav"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "1250"
					spawnflags = "49"
					spindown = "0"
					spinup = "0"
					targetname = "ralimu_survival_radio_sound2"
					volstart = "0"
					origin = Vector( 11020, -5992, -24 )
				}
			}
			ralimu_survival_radio_sound3 =
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					angles = Vector( 0, 0, 0 )
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "ambient/energy/zap3.wav"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "1250"
					spawnflags = "49"
					spindown = "0"
					spinup = "0"
					targetname = "ralimu_survival_radio_sound3"
					volstart = "0"
					origin = Vector( 11020, -6008, -24 )
				}
			}
			ralimu_survival_navattrs2 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10576, -5782.08, 120 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "32"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 28, 30, 24 )
				}
			}
			ralimu_survival_navattrs3 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10232, -5829.98, 120 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "32"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 28, 30, 24 )
				}
			}
			ralimu_survival_navattrs4 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10888, -5999.73, 132 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "32"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 28, 30, 24 )
				}
			}
			ralimu_survival_navattrs5 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10892, -5749.98, 132 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "32"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 28, 30, 24 )
				}
			}
			ralimu_survival_items68 =
			{
				SpawnInfo =
				{
					classname = "weapon_smg_spawn"
					angles = Vector( 8, 50, -90 )
					body = "0"
					count = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					glowrange = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					texframeindex = "0"
					weaponskin = "-1"
					origin = Vector( 10284, -4607, 117 )
				}
			}
			ralimu_survival_items69 =
			{
				SpawnInfo =
				{
					classname = "weapon_shotgun_spas_spawn"
					angles = Vector( -75, 270, 90 )
					count = "2"
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10952, -4592, -64 )
				}
			}
			ralimu_survival_items70 =
			{
				SpawnInfo =
				{
					classname = "weapon_pain_pills_spawn"
					angles = Vector( 0, 210.5, 0 )
					disableshadows = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10966, -4590, -63 )
				}
			}
			ralimu_survival_navattrs6 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10942, -6920, 232 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "256"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 1122, 3240, 808 )
				}
			}
			ralimu_survival_navattrs7 =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 10334, -3472, -305.75 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "256"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navattrs"
					extent = Vector( 514, 208, 224 )
				}
			}
			ralimu_survival_items71 =
			{
				SpawnInfo =
				{
					classname = "weapon_adrenaline_spawn"
					angles = Vector( 0, 278, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10850, -6060, 161 )
				}
			}
			ralimu_survival_items72 =
			{
				SpawnInfo =
				{
					classname = "weapon_adrenaline_spawn"
					angles = Vector( 0, 278, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10696, -5715.29, -40 )
				}
			}
			ralimu_survival_items73 =
			{
				SpawnInfo =
				{
					classname = "weapon_molotov_spawn"
					angles = Vector( 0, 214, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10861, -6062, 166 )
				}
			}
			ralimu_survival_items74 =
			{
				SpawnInfo =
				{
					classname = "weapon_ammo_spawn"
					angles = Vector( 0, 226, 0 )
					count = "0"
					disableshadows = "0"
					model = "models/props/terror/ammo_stack.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10960, -8560, 24 )
				}
			}
			ralimu_survival_finder_ammo_filter1 =
			{
				SpawnInfo =
				{
					classname = "filter_activator_name"
					angles = Vector( 0, 0, 0 )
					filtername = "ammo_spawn1"
					negated = "0"
					targetname = "ralimu_survival_finder_ammo_filter1"
					origin = Vector( 10760, -7384, 0 )
				}
			}
			ralimu_survival_finder_ammo1 =
			{
				SpawnInfo =
				{
					classname = "point_entity_finder"
					angles = Vector( 0, 0, 0 )
					filtername = "ralimu_survival_finder_ammo_filter"
					method = "0"
					referencename = "ammo_spawn1_template"
					targetname = "ralimu_survival_finder_ammo1"
					origin = Vector( 10776, -7384, 0 )
					connections =
					{
						OnFoundEntity =
						{
							cmd1 = "!callerKill0-1"
						}
					}
				}
			}
			ralimu_survival_props6 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1200"
					fadescale = "0.5"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 11254, -4578, -202 )
				}
			}
			ralimu_survival_props7 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					drawinfastreflection = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "1500"
					fademindist = "1200"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 11261, -4578, -211 )
				}
			}
			ralimu_survival_props8 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					maxanimtime = "10"
					minanimtime = "5"
					model = "models/props/cs_militia/ladderrung.mdl"
					physdamagescale = "1.0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "ralimu_survival_props"
					origin = Vector( 11264, -4576, -280 )
				}
			}
			ralimu_survival_props9 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					maxanimtime = "10"
					minanimtime = "5"
					model = "models/props/cs_militia/ladderrung.mdl"
					physdamagescale = "1.0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "ralimu_survival_props"
					origin = Vector( 11245, -4579, -195 )
				}
			}
			ralimu_survival_navobstruct =
			{
				SpawnInfo =
				{
					classname = "script_nav_attribute_region"
					crouch = "0"
					mob_only = "0"
					origin = Vector( 11160, -3926, -464 )
					precise = "0"
					remove_attributes = "0"
					spawnflags = "0"
					stairs = "0"
					tank_only = "0"
					targetname = "ralimu_survival_navobstruct"
					extent = Vector( 88, 90, 112 )
				}
				PostPlaceCB = function(entity, rarity)
				{
					local areas = {}; NavMesh.GetNavAreasOverlappingEntityExtent(self, areas);
					foreach( area in areas )
						area.MarkAsDamaging( 1 << 16 );
				}
			}
			ralimu_survival_template =
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					angles = Vector( 0, 0, 0 )
					spawnflags = "2"
					targetname = "ralimu_survival_template"
					Template01 = "ralimu_survival_items"
					Template02 = "ralimu_survival_radio"
					Template03 = "ralimu_survival_radio_button"
					Template04 = "ralimu_survival_radio_hint"
					Template05 = "ralimu_survival_navattrs"
					Template06 = "ralimu_survival_navobstruct"
					Template07 = "ralimu_survival_finder_ammo1"
					Template08 = "ralimu_survival_finder_ammo_filter1"
					Template09 = "ralimu_survival_finder_ammo2"
					Template10 = "ralimu_survival_finder_ammo_filter2"
					Template12 = "ralimu_survival_radio_sound_case"
					Template13 = "ralimu_survival_radio_sound1"
					Template14 = "ralimu_survival_radio_sound2"
					Template15 = "ralimu_survival_radio_sound3"
					Template16 = "ralimu_survival_radio_sparks"
					vscripts = "entityscripts/c12m4_ralimu_pointtemplate"
					origin = Vector( 10992, -5984, -36 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "ralimu_survival_radioStartGlowing3-1"
							cmd2 = "ralimu_survival_radio_hintShowHint2-1"
							cmd3 = "ralimu_survival_navattrsApplyNavAttributes0-1"
							cmd4 = "ralimu_survival_finder_ammo1FindEntity0-1"
							cmd5 = "!selfCallScriptFunctionOnEntitySpawned1-1"
							cmd6 = "ralimu_survival_finder_ammo2FindEntity0-1"
						}
					}
				}
			}
			ralimu_survival_items75 =
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 165, 0 )
					body = "0"
					count = "1"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10971, -8728, 27 )
				}
			}
			ralimu_survival_items76 =
			{
				SpawnInfo =
				{
					classname = "weapon_adrenaline_spawn"
					angles = Vector( 0, 250, 0 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10892, -8565, 23 )
				}
			}
			ralimu_survival_items77 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -4, 320, -0.571294 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_junk/propanecanister001a.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11120, -9101, -64 )
				}
			}
			ralimu_survival_items78 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 345, -8 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_equipment/oxygentank01.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11105, -9089, -76 )
				}
			}
			ralimu_survival_items79 =
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 294, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_junk/propanecanister001a.mdl"
					physdamagescale = "0.1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "256"
					targetname = "ralimu_survival_items"
					origin = Vector( 11571.5, -8262, -57 )
				}
			}
			ralimu_survival_vphysics_clip =
			{
				SpawnInfo =
				{
					classname = "script_clip_vphysics"
					origin = Vector( 10456, -3644, 80.35 )
					spawnflags = "0"
					targetname = "ralimu_survival_vphysics_clip"
					extent = Vector( 104, 36, 151.6488 )
				}
			}
			ralimu_survival_items80 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 87.6523, 315, -89.0662 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10926, -5951, -35 )
				}
			}
			ralimu_survival_items81 =
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 87.6523, 79, -89.0662 )
					body = "0"
					disableshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					solid = "6"
					spawnflags = "2"
					targetname = "ralimu_survival_items"
					weaponskin = "-1"
					origin = Vector( 10892, -5948, -35 )
				}
			}
			ralimu_survival_props10 =
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 90, 270, 0 )
					body = "0"
					disableflashlight = "0"
					disablereceiveshadows = "0"
					disableshadowdepth = "0"
					disableshadows = "0"
					effects = "0"
					explodedamage = "0"
					explodemagnitude = "0"
					exploderadius = "0"
					fademaxdist = "600"
					fademindist = "600"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					lagcompensate = "0"
					maxanimtime = "10"
					minanimtime = "5"
					minhealthdmg = "0"
					model = "models/props_wasteland/controlroom_desk001b.mdl"
					performancemode = "0"
					physdamagescale = "1.0"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					setbodygroup = "0"
					shadowcastdist = "0"
					shadowdepthnocache = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					startdisabled = "0"
					targetname = "ralimu_survival_props"
					texframeindex = "0"
					origin = Vector( 10444, -3640, -44 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // C12M4RalimuSurvival

RegisterEntityGroup( "C12M4RalimuSurvival", C12M4RalimuSurvival )
